### ISSUE TITLE
Use SNodePointer in the editor

### ISSUE THREAD

**Issue by slisson** [slisson/shadowmodels#150]
```
Caused by: java.lang.ClassCastException: de.q60.mps.shadowmodels.runtime.smodel.ANodeReference cannot be cast to jetbrains.mps.smodel.SNodePointer
	at jetbrains.mps.smodel.SNodePointer.serialize(SNodePointer.java:112)
	at jetbrains.mps.nodeEditor.Memento.save(Memento.java:310)
	at jetbrains.mps.nodeEditor.MementoPersistence.saveMemento(MementoPersistence.java:27)
	at jetbrains.mps.ide.editor.BaseNodeEditor$BaseEditorState.save(BaseNodeEditor.java:368)
	at jetbrains.mps.ide.editor.MPSFileNodeEditorProvider.writeState(MPSFileNodeEditorProvider.java:108)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.lambda$writeExternal$0(HistoryEntry.java:170)
	at java.util.Map.forEach(Map.java:630)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.writeExternal(HistoryEntry.java:162)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.getState(EditorHistoryManager.java:344)
	at com.intellij.openapi.fileEditor.impl.EditorHistoryManager.getState(EditorHistoryManager.java:31)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:259)
	at com.intellij.configurationStore.ComponentStoreImpl.saveComponents(ComponentStoreImpl.kt:203)
	... 24 more

```

**Comment by slisson** [comment]
```
org.jetbrains.mps.openapi.persistence.PersistenceFacade$IncorrectNodeIdFormatException: No delimiter discovered in the passed argument de.q60.mps.shadowmodels.runtime.smodel.ANodeReference@2c5d35c0
	at jetbrains.mps.smodel.SNodePointer.deserialize(SNodePointer.java:119)
	at jetbrains.mps.persistence.PersistenceRegistry.createNodeReference(PersistenceRegistry.java:269)
	at jetbrains.mps.nodeEditor.cells.DefaultCellInfo.loadFrom(DefaultCellInfo.java:128)
	at jetbrains.mps.nodeEditor.selection.SelectionInfoImpl.<init>(SelectionInfoImpl.java:71)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at jetbrains.mps.nodeEditor.Memento.load(Memento.java:380)
	at jetbrains.mps.nodeEditor.MementoPersistence.loadMemento(MementoPersistence.java:32)
	at jetbrains.mps.ide.editor.BaseNodeEditor$BaseEditorState.load(BaseNodeEditor.java:384)
	at jetbrains.mps.ide.editor.MPSFileNodeEditorProvider.readState(MPSFileNodeEditorProvider.java:86)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.parseEntry(HistoryEntry.java:205)
	at com.intellij.openapi.fileEditor.impl.HistoryEntry.createLight(HistoryEntry.java:73)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:848)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$UIBuilder.processFiles(EditorsSplitters.java:819)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters$ConfigTreeReader.process(EditorsSplitters.java:810)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.openFiles(EditorsSplitters.java:239)
	at com.intellij.openapi.fileEditor.impl.OpenFilesActivity.runActivity(OpenFilesActivity.java:34)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runAndMeasure(StartupManagerImpl.java:164)
	at com.intellij.ide.startup.impl.StartupManagerImpl.logActivityDuration(StartupManagerImpl.java:150)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runPostStartupActivitiesFromExtensions$1(StartupManagerImpl.java:138)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:356)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivitiesFromExtensions(StartupManagerImpl.java:140)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$openProject$8(ProjectManagerImpl.java:409)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadProjectUnderProgress(ProjectManagerImpl.java:440)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:423)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:501)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:492)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:320)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
