### ISSUE TITLE
When I try to run sm2java on sm1, I get an exception

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#28]
Exception is below; please advise if I should rather run another example because this one is currently not supported?

------------------------------

at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[100847342]   WARN - or.cells.EditorCellFactoryImpl - Failed to create cell for node: [type] ClassifierType null[NodeToSNodeAdapter[de.q60.mps.shadowmodel.runtime.ResultElementAsNode@aa5282dc]] in shadowmodels.dummy.model1 using default editor [node de.q60.mps.shadowmodel.runtime.smodel.ANodeReference@475649f8] 
java.lang.UnsupportedOperationException: Querying the parent of a reference target is not supported. ClassifierType.classifier
	at de.q60.mps.shadowmodel.runtime.ContainmentData$2.getParent(ContainmentData.java:24)
	at de.q60.mps.shadowmodel.runtime.ResultElementAsNode.getParent(ResultElementAsNode.java:42)
	at de.q60.mps.shadowmodel.runtime.smodel.NodeToSNodeAdapter.getParent(NodeToSNodeAdapter.java:121)
	at de.q60.mps.shadowmodel.runtime.smodel.ANode.treeParent(ANode.java:317)
	at jetbrains.mps.smodel.SNode.getParent(SNode.java:148)
	at jetbrains.mps.smodel.SNode.getParent(SNode.java:48)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.getNodeAncestors(SNodeOperations.java:171)
	at jetbrains.mps.baseLanguage.behavior.Classifier__BehaviorDescriptor.getNestedNameInContext_id7q4lzBFjvF8(Classifier__BehaviorDescriptor.java:191)
	at jetbrains.mps.baseLanguage.behavior.Classifier__BehaviorDescriptor.invokeSpecial0(Classifier__BehaviorDescriptor.java:589)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:345)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtualCommon(BaseBHDescriptor.java:293)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeNonVirtual(BaseBHDescriptor.java:269)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:230)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at jetbrains.mps.baseLanguage.editor.PresentationProviders$3.getPresentation(PresentationProviders.java:33)
	at jetbrains.mps.nodeEditor.cells.EditorCell_RefPresentation$MyAccessor.getText(EditorCell_RefPresentation.java:65)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Property.<init>(EditorCell_Property.java:41)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Property.create(EditorCell_Property.java:58)
	at jetbrains.mps.nodeEditor.cells.EditorCell_RefPresentation.create(EditorCell_RefPresentation.java:46)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a$Inline_Builder0.createReferencePresentation_0(ClassifierType_EditorBuilder_a.java:154)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a$Inline_Builder0.createCell(ClassifierType_EditorBuilder_a.java:144)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a$1$1.compute(ClassifierType_EditorBuilder_a.java:92)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a$1$1.compute(ClassifierType_EditorBuilder_a.java:90)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.updateReferencedNodeCell(UpdateSessionImpl.java:297)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a$1.createReferenceCell(ClassifierType_EditorBuilder_a.java:90)
	at jetbrains.mps.lang.editor.cellProviders.SReferenceCellProvider.createCell(SReferenceCellProvider.java:87)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a.createRefCell_0(ClassifierType_EditorBuilder_a.java:110)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a.createCollection_0(ClassifierType_EditorBuilder_a.java:77)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_EditorBuilder_a.createCell(ClassifierType_EditorBuilder_a.java:69)
	at jetbrains.mps.baseLanguage.editor.ClassifierType_Editor.createEditorCell(ClassifierType_Editor.java:12)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:121)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:104)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:82)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a.createNextEditor_2(BaseConcept_conditionalEditor_EditorBuilder_a.java:244)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a.createAlternation_0(BaseConcept_conditionalEditor_EditorBuilder_a.java:65)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a.createPriorityInfoCell_0(BaseConcept_conditionalEditor_EditorBuilder_a.java:51)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a.createPriorityInfoCell_1(BaseConcept_conditionalEditor_EditorBuilder_a.java:56)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a.createCell(BaseConcept_conditionalEditor_EditorBuilder_a.java:46)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_Editor_Tracing.createEditorCell(BaseConcept_conditionalEditor_Editor_Tracing.java:22)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:121)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:104)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:82)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a_0.createNextEditor_1(BaseConcept_conditionalEditor_EditorBuilder_a_0.java:100)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a_0.createAlternation_0(BaseConcept_conditionalEditor_EditorBuilder_a_0.java:58)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a_0.createPriorityInfoCell_0(BaseConcept_conditionalEditor_EditorBuilder_a_0.java:44)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a_0.createPriorityInfoCell_1(BaseConcept_conditionalEditor_EditorBuilder_a_0.java:49)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_EditorBuilder_a_0.createCell(BaseConcept_conditionalEditor_EditorBuilder_a_0.java:39)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_Editor_Coloring.createEditorCell(BaseConcept_conditionalEditor_Editor_Coloring.java:22)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:121)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:104)

**Comment by slisson** [comment]
You can disable the exception in ResultElementAsNode.getReferenceTarget by replacing ContainmentData.unknown(this, role) with ContainmentData.NULL.

**Comment by slisson** [comment]
Relates to #18

**Comment by markusvoelter** [comment]
Works, no more exception. But also, the trafo result is not updated when I edit the source. What am I missing?
