### ISSUE TITLE
What exactly does applyRecursively do?

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#74]
<img width="536" alt="screen shot 2018-12-17 at 08 12 56" src="https://user-images.githubusercontent.com/592330/50071914-ab966c00-01d3-11e9-844b-7f7c6e033c7f.png">

I thought it applied recursively (descendants) to only Exprs because this is the input of the trafo

But I get an exception that seems as if the engine tried it for *all* descendants, incl. the ElsePart, which is not an Expr:

t.EventDispatchThread.run(EventDispatchThread.java:82)
[40019748]  ERROR - untime.smodel.NodeSynchronizer -  
de.q60.mps.polymorphicfunctions.runtime.NoApplicableImplementationException: No applicable implementation found for de.q60.mps.shadowmodels.examples.expressions.transformations.Desugar.desugar(°ElsePart)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.getImplementationsToCall(DefaultPFContext.java:53)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunctions(DefaultPFContext.java:39)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:30)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.selectRule(TransformationEngine.java:127)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.solveProblem(TransformationEngine.java:118)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:103)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:1)
	at de.q60.mps.shadowmodels.runtime.incremental.DependencyBroadcaster.evaluateWithTracking(DependencyBroadcaster.java:20)
	at de.q60.mps.shadowmodels.runtime.incremental.IncrementalEngine.evaluateWithTracking(IncrementalEng

**Comment by slisson** [comment]
#88

**Comment by slisson** [comment]
Concept doesn't exist anymore. Was introduced for the desugaring use case. Forks with auto applied transformations now cover this use case.
