### ISSUE TITLE
Exception in multi-parameter Trafo call

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#75]
![screen shot 2018-12-17 at 09 23 20](https://user-images.githubusercontent.com/592330/50074971-df768f00-01dd-11e9-9139-3cd0a1fd154c.png)

I get:

[43217921]  ERROR - untime.smodel.NodeSynchronizer -  
de.q60.mps.polymorphicfunctions.runtime.NoApplicableImplementationException: No applicable implementation found for de.q60.mps.shadowmodels.examples.expressions.transformations.Repo.t13(°red, °Color)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.getImplementationsToCall(DefaultPFContext.java:53)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunctions(DefaultPFContext.java:39)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:30)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.selectRule(TransformationEngine.java:127)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.solveProblem(TransformationEngine.java:118)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:103)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:1)
	at de.q60.mps.shadowmodels.runtime.incremental.DependencyBroadcaster.evaluateWithTracking(DependencyBroadcaster.java:20)
	at de.q60.mps.shadowmodels.runtime.incremental.IncrementalEngine.evaluateWithTracking(IncrementalEngine.java:117)
	at de.q60.mps.shadowmodels.runtime.incremental.IncrementalEngine.evaluate(IncrementalEngine.java:109)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.updateResult(TransformationEngine.java:94)
	at de.q60.mps.shadowmodels.runtime.TransformationResult$TransformationResultChild.resolve(TransformationResult.java:313)
	at de.q60.mps.shadowmodels.runtime.TransformationResult$1.translate(TransformationResult.java:55)
	at de.q60.mps.shadowmodels.runtime.TransformationResult$1.translate(TransformationResult.java:1)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:12)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:7)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.moveToNext(TranslatingSequence.java:82)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.hasNext(TranslatingSequence.java:37)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.moveToNext(TranslatingSequence.java:66)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.hasNext(TranslatingSequence.java:37)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
	at jetbrains.mps.internal.collections.runtime.ListSequence.fromIterable(ListSequence.java:122)
	at jetbrains.mps.internal.collections.runtime.AbstractSequence.toListSequence(AbstractSequence.java:215)
	at de.q60.mps.shadowmodels.runtime.smodel.NodeSynchronizer.synchronizeChildren(NodeSynchronizer.java:119)
	at de.q60.mps.shadowmodels.runtime.smodel.NodeSynchronizer.synchronizeNode(NodeSynchronizer.java:105)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager.synchronizeRootNodes(RepositoryModulesManager.java:236)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager.synchronizeModel(RepositoryModulesManager.java:224)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager.synchronizeModule(RepositoryModulesManager.java:201)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager.synchronizeRepository(RepositoryModulesManager.java:164)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager.synchronizeAll(RepositoryModulesManager.java:142)
	at de.q60.mps.shadowmodels.runtime.smodel.RepositoryModulesManager$4$1.invoke(RepositoryModulesManager.java:126)
	at de.q60.mps.shadowmodels.runtime.smodel.CommandHelper$2.run(CommandHelper.java:26)
	at jetbrains.mps.smodel.WorkbenchModelAccess$UndoContextSetup.run(WorkbenchModelAccess.java:360)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:84)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:100)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:84)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:100)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at jetbrains.mps.smodel.TryRunPlatformWriteHelper.runWrite(TryRunPlatformWriteHelper.java:103)

**Comment by markusvoelter** [comment]
Branch: markus-shadow
Trafo: http://127.0.0.1:63320/node?ref=r%3A49e489bb-f00f-4c40-a675-08c681da1ac3%28de.q60.mps.shadowmodels.examples.expressions.transformations%29%2F7244744932403433892&project=mps-extensions

**Comment by slisson** [comment]
Is this issue still valid or does it work now? The transformation doesn't exist anymore on that branch.

**Comment by markusvoelter** [comment]
I deleted the code so I could move on, trying out SM. But it was still valid. It might, however, be related to #76 . I will try it again if #76 is solved, ok?

**Comment by slisson** [comment]
Can reproduce it now. Working in it.
