### ISSUE TITLE
How do I control the order of evaluation?

### ISSUE THREAD

**Issue by markusvoelter** [slisson/shadowmodels#77]
Top down vs. Bottom up? The "interpreter" I am trying to build does not work.

Source:
![screen shot 2018-12-17 at 10 14 41](https://user-images.githubusercontent.com/592330/50077416-9f66da80-01e4-11e9-8fa6-d757bb3a4d2d.png)

Result:
![screen shot 2018-12-17 at 10 14 45](https://user-images.githubusercontent.com/592330/50077428-a68de880-01e4-11e9-915b-a75f271655d7.png)

How do I schedule several transformations? For example, first "desugar" the program and then "run" the execute declarations?

**Comment by markusvoelter** [comment]
Nesting does not work:

![screen shot 2018-12-17 at 10 39 17](https://user-images.githubusercontent.com/592330/50078743-0d60d100-01e8-11e9-89c3-44d94ddbab67.png)


INFO - ps.classloading.ModulesWatcher - Totally 0 modules are marked invalid for class loading: 
[  55069]  ERROR - untime.smodel.NodeSynchronizer -  
de.q60.mps.polymorphicfunctions.runtime.NoApplicableImplementationException: No applicable implementation found for de.q60.mps.shadowmodels.examples.expressions.transformations.Repo.execute(°de.q60.mps.shadowmodels.examples.expressions.transformations.Repo.processDecl(c)->Constant)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.getImplementationsToCall(DefaultPFContext.java:53)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunctions(DefaultPFContext.java:39)
	at de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:30)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.selectRule(TransformationEngine.java:127)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.solveProblem(TransformationEngine.java:118)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:103)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine$4.invoke(TransformationEngine.java:1)
	at de.q60.mps.shadowmodels.runtime.incremental.DependencyBroadcaster.evaluateWithTracking(DependencyBroadcaster.java:20)
	at de.q60.mps.shadowmodels.runtime.incremental.IncrementalEngine.evaluateWithTracking(IncrementalEngine.java:117)
	at de.q60.mps.shadowmodels.runtime.incremental.IncrementalEngine.evaluate(IncrementalEngine.java:109)
	at de.q60.mps.shadowmodels.runtime.TransformationEngine.updateResult(TransformationEngine.java:94)
	at de.q60.mps.shadowmodels.runtime.TransformationResult$TransformationResultChild.resolve(TransformationResult.java:313)
	at de.q60.mps.shadowmodels.runtime.TransformationResult$TransformationResultChild.asNode(TransformationResult.java:317)
	at de.q60.mps.shadowmodels.runtime.ResultElementAsNode$1.translate(ResultElementAsNode.java:52)
	at de.q60.mps.shadowmodels.runtime.ResultElementAsNode$1.translate(ResultElementAsNode.java:1)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:12)
	at jetbrains.mps.internal.collections.runtime.ITranslator2.invoke(ITranslator2.java:7)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.moveToNext(TranslatingSequence.java:82)
	at jetbrains.mps.internal.collections.runtime.impl.TranslatingSequence$TranslatingIterator.hasNext(TranslatingSequence.java:37)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
	at jetbrains.mps.internal.collections.runtime.ListSequence.fromIterable(ListSequence.java:122)

**Comment by slisson** [comment]
>  No applicable implementation found for de.q60.mps.shadowmodels.examples.expressions.transformations.Repo.execute(°de.q60.mps.shadowmodels.examples.expressions.transformations.Repo.processDecl(c)->Constant)

That means `processDecl` returns a `Constant` and there is no `execute` transformation that applies to a `Constant`.

**Comment by markusvoelter** [comment]
ok. 

So the way to schedule trafos is to nest their calls. Correct?

**Comment by slisson** [comment]
yes

**Comment by markusvoelter** [comment]
Ok.
